### ISSUE TITLE
Server and Client Error on 1.19.3

### ISSUE THREAD

**Issue by sternschnaube** [Ivan-1F/Ivan-Carpet-Addition#15]
https://pastebin.com/raw/ZZFZ4DXK

**Comment by Ivan-1F** [comment]
Please provide a list of mods you installed

**Comment by venaminecraft** [comment]
https://pastebin.com/raw/ArLa3fgW

**Comment by Ivan-1F** [comment]
Emm that's tons of mods, I will suggested you to figure out which mod that causes the conflict

Please test with a minimum environment and see if the exception would occured

**Comment by venaminecraft** [comment]
That's the crash result from the client, maybe it helps: https://pastebin.com/raw/Da7BuYZq
I was thinking, if old saved rules can cause this - but this is not the case.

I will spot the incompatibility and tell you then 👍🏿

**Comment by Aculoss** [comment]
same here

**Comment by Aculoss** [comment]
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'carpet'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:102) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.11.jar:?]
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: java.lang.ClassCastException@290b3122
	at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.parseRule(CarpetRuleRegistrar.java:52) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?]
	at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.parseSettingsClass(CarpetRuleRegistrar.java:31) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?]
	at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.register(CarpetRuleRegistrar.java:23) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?]
	at me.ivan.ivancarpetaddition.IvanCarpetAdditionServer.onGameStarted(IvanCarpetAdditionServer.java:57) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at carpet.CarpetServer.onGameStarted(CarpetServer.java:82) ~[fabric-carpet-1.19.3-1.4.91+v221207.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy72.onInitializeServer(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
	... 7 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@290b3122
	at jdk.internal.reflect.GeneratedConstructorAccessor91.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.parseRule(CarpetRuleRegistrar.java:46) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?]
	at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.parseSettingsClass(CarpetRuleRegistrar.java:31) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?]
	at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.register(CarpetRuleRegistrar.java:23) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?]
	at me.ivan.ivancarpetaddition.IvanCarpetAdditionServer.onGameStarted(IvanCarpetAdditionServer.java:57) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at carpet.CarpetServer.onGameStarted(CarpetServer.java:82) ~[fabric-carpet-1.19.3-1.4.91+v221207.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy72.onInitializeServer(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
	... 7 more

**Comment by Ivan-1F** [comment]
> java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'carpet'! at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.11.jar:?] at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.11.jar:?] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.11.jar:?] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?] at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.11.jar:?] at net.minecraft.server.Main.main(Main.java:102) ~[server-intermediary.jar:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.11.jar:?] at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.11.jar:?] Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: java.lang.ClassCastException@290b3122 at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.parseRule(CarpetRuleRegistrar.java:52) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?] at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.parseSettingsClass(CarpetRuleRegistrar.java:31) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?] at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.register(CarpetRuleRegistrar.java:23) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?] at me.ivan.ivancarpetaddition.IvanCarpetAdditionServer.onGameStarted(IvanCarpetAdditionServer.java:57) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?] at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] at carpet.CarpetServer.onGameStarted(CarpetServer.java:82) ~[fabric-carpet-1.19.3-1.4.91+v221207.jar:?] at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?] at com.sun.proxy.jdk.proxy3.$Proxy72.onInitializeServer(Unknown Source) ~[?:?] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?] ... 7 more Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@290b3122 at jdk.internal.reflect.GeneratedConstructorAccessor91.newInstance(Unknown Source) ~[?:?] at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.parseRule(CarpetRuleRegistrar.java:46) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?] at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.parseSettingsClass(CarpetRuleRegistrar.java:31) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?] at me.ivan.ivancarpetaddition.settings.CarpetRuleRegistrar.register(CarpetRuleRegistrar.java:23) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?] at me.ivan.ivancarpetaddition.IvanCarpetAdditionServer.onGameStarted(IvanCarpetAdditionServer.java:57) ~[ivan-carpet-addition-mc1.19.3-v2.2.1.jar:?] at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] at carpet.CarpetServer.onGameStarted(CarpetServer.java:82) ~[fabric-carpet-1.19.3-1.4.91+v221207.jar:?] at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?] at com.sun.proxy.jdk.proxy3.$Proxy72.onInitializeServer(Unknown Source) ~[?:?] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?] ... 7 more

Please provide the full log contains the mod list

**Comment by venaminecraft** [comment]
Hello @Ivan-1F and @Hendrix-Shen. 
I was spotting now the problem 😊

It's the MagicLib: https://github.com/Hendrix-Shen/MagicLib
Which is as well on Server side present.

Maybe you can look into that from your side too, Hendrix. Thanks already.

**Comment by Ivan-1F** [comment]
try https://github.com/Ivan-1F/Ivan-Carpet-Addition/actions/runs/3939558527

**Comment by venaminecraft** [comment]
Hello @Ivan-1F, client and server starting without any problems.
Activating rules on the server works also.
I was not testing a rule yet in-game, but everything looks perfect now - thank you so much again 🥳
