### ISSUE TITLE
runing ica in 1.19.3,Unable to launch the game

### ISSUE THREAD

**Issue by MICOAST** [Ivan-1F/Ivan-Carpet-Addition#17]
latest log：
[07:12:11] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[07:12:12] [ForkJoinPool-1-worker-4/WARN]: Mod litematica_printer uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:12] [ForkJoinPool-1-worker-3/WARN]: Mod com_github_senseiwells_arucas uses the version d443072775 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'd443072775'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[07:12:12] [main/INFO]: Loading 142 mods:
	- appleskin 2.4.2+mc1.19.3
	- axolotlitemfix 1.1.4
	- badpackets 0.3.4
	- bedrockminer 2.1
	- betterpingdisplay 1.1.1
	- betterthanmending 1.3.0
	- boostedbrightness 2.1.2
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- carpet 1.4.93
	- carpet-ams-addition 1.3.5
	- carpet-extra 1.4.91
	- carpet-fixes 1.19.3-1.13.0
	- chat_heads 0.9.0
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 9.0.94 via appleskin
	- com_akuleshov7_ktoml-core-jvm 0.3.0 via zoomify
	- com_github_llamalad7_mixinextras 0.1.1 via zoomify
	- com_github_senseiwells_arucas d443072775 via essential-client
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- conditional-mixin 0.3.2 via ivan-carpet-addition
	- creativecore 2.9.3
	- customskinloader 14.15.1
	- dev_isxander_settxi_settxi-core 2.10.6 via zoomify
	- dev_isxander_settxi_settxi-gui 2.10.6 via zoomify
	- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6 via zoomify
	- easiervillagertrading 1.19.3-fabric0.68.1-1.5.4
	- entityculling 1.5.2-mc1.19.3
	- essential-client 1.3.2
	- fabric-api 0.72.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.29+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.11+1134c5b885 via fabric-api
	- fabric-command-api-v1 1.2.21+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.0+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.38+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.46+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.4+1134c5b885 via fabric-api
	- fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.42+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.8+1134c5b885 via fabric-api
	- fabric-item-group-api-v1 2.1.11+1134c5b885 via fabric-api
	- fabric-key-binding-api-v1 1.0.30+bc01e09785 via fabric-api
	- fabric-keybindings-v0 0.2.28+df3654b385 via fabric-api
	- fabric-language-kotlin 1.9.0+kotlin.1.8.0
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.26+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.33+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.3.0+85f102ee85 via fabric-api
	- fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.0+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.4+1134c5b885 via fabric-api
	- fabric-renderer-api-v1 2.2.0+9f179aa185 via fabric-api
	- fabric-renderer-indigo 0.7.0+9f179aa185 via fabric-api
	- fabric-renderer-registries-v1 3.2.29+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
	- fabric-rendering-v0 1.1.32+df3654b385 via fabric-api
	- fabric-rendering-v1 1.12.0+6dc0edd785 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.2+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
	- fabric-screen-api-v1 1.0.40+f1e4495b85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
	- fabric-sound-api-v1 1.0.7+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.14+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
	- fabricloader 0.14.12
	- gbfabrictools 1.3.4+1.19.3 via easiervillagertrading
	- gca 2.4.1-1.19
	- imblocker 1.0.20
	- inventoryhud 3.4.7
	- inventoryprofilesnext 1.9.1
	- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
	- iris 1.5.1
	- itemphysic 1.6.7
	- itemscroller 0.18.0
	- ivan-carpet-addition 2.2.1
	- java 17
	- kyrptconfig 1.5.1-1.19.3 via quickshulker
	- libipn 2.0.1
	- litematica 0.13.1
	- litematica_printer ${version}
	- lithium 0.10.4
	- magiclib 0.6.200+a47eb26-beta
	- magiclib-1_19_3 0.6.200+a47eb26-beta via magiclib
	- malilib 0.14.0
	- masa_gadget_mod 3.0.0-beta+f5856ee
	- masa_gadget_mod-1_19_3 3.0.0-beta+f5856ee via masa_gadget_mod
	- minecraft 1.19.3
	- minihud 0.25.0
	- modmenu 5.0.2
	- nochatreports 1.19.3-v1.19.0
	- ommc 0.5-beta+20ce4cc
	- ommc-1_19_3 0.5-beta+20ce4cc via ommc
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_yaml_snakeyaml 1.29 via ivan-carpet-addition
	- pearltickets 1.19.2-1.1.4
	- phosphor 0.8.1
	- quickshulker 1.3.10-1.19.3
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- replaymod 1.19.3-2.6.10
	- settxi-gui-yacl 2.10.6 via zoomify
	- shulkerutils 1.0.4-1.19 via quickshulker
	- skinlayers 1.5.2-mc1.19.3
	- smoothswapping 0.6.1
	- sodium 0.4.8+build.22
	- sodium-extra 0.4.16+mc1.19.3-build.91
	- syncmatica 1.18.2-0.3.8
	- tweakermore 3.9.2
	- tweakeroo 0.15.0
	- tweakmyclient 3.4.303+867af56-beta
	- tweakmyclient-1_19_3 3.4.303+867af56-beta via tweakmyclient
	- wthit 6.1.2
	- xaerominimap 22.17.0
	- xaeroworldmap 1.28.7
	- yet-another-config-lib 2.2.0
	- zoomify 2.9.2
[07:12:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/F:/Minecraft%20PCL/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[07:12:13] [main/INFO]: Compatibility level set to JAVA_17
[07:12:13] [main/WARN]: Reference map 'axolotl-item-fix-refmap.json' for axolotlitemfix.mixins.json could not be read. If this is a development environment you can ignore this message
[07:12:14] [main/INFO]: Loaded configuration file for Lithium: 106 options available, 0 override(s) found
[07:12:14] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[07:12:14] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 1 override(s) found
[07:12:14] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 0 override(s) found
[07:12:16] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[07:12:17] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[07:12:17] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[07:12:17] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[07:12:17] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[07:12:21] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[07:12:21] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[07:12:22] [main/WARN]: Method overwrite conflict for method_5800 in carpet-fixes.mixins.json:itemFixes.ItemEntity_lightningKillsDropsMixin from mod carpet-fixes, previously written by carpet.mixins.ItemEntityMixin. Skipping method.
[07:12:28] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::negativeLimit(I)I with priority 1000
[07:12:28] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[07:12:28] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::negativeLimit(I)I with priority 1000
[07:12:28] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[07:12:28] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::negativeLimit(I)I with priority 1000
[07:12:28] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[07:12:28] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[07:12:28] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[07:12:28] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity from mod tweakeroo->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockEntity_limitsMixin from mod carpet->@ModifyConstant::positiveLimit(I)I with priority 1000
[07:12:31] [main/INFO]: Building optimized datafixer
[07:12:42] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[07:12:42] [Render thread/INFO]: Launching a new process to probe the system configuration!
[07:12:43] [Render thread/INFO]: OpenGL Vendor: Intel
[07:12:43] [Render thread/INFO]: OpenGL Renderer: Intel(R) UHD Graphics
[07:12:43] [Render thread/INFO]: OpenGL Version: 3.3.0 - Build 27.20.100.9316
[07:12:43] [Render thread/INFO]: Mixing client.MixinMinecraft from nochatreports.mixins.json into net.minecraft.class_310
[07:12:43] [Render thread/INFO]: Mixing client.MixinTitleScreen from nochatreports.mixins.json into net.minecraft.class_442
[07:12:44] [Render thread/INFO]: Mixing client.MixinChatScreen from nochatreports.mixins.json into net.minecraft.class_408
[07:12:44] [Render thread/INFO]: Renaming synthetic method lambda$onInit$4()Lnet/minecraft/class_2561; to md590d4e$lambda$onInit$4$0 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[07:12:44] [Render thread/INFO]: Renaming synthetic method lambda$onInit$3(Lnet/minecraft/class_4185;)V to md590d4e$lambda$onInit$3$1 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[07:12:44] [Render thread/INFO]: Renaming synthetic method lambda$onInit$2()Lnet/minecraft/class_2561; to md590d4e$lambda$onInit$2$2 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[07:12:44] [Render thread/INFO]: Renaming synthetic method lambda$onInit$1(Lnet/minecraft/class_4185;)V to md590d4e$lambda$onInit$1$3 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[07:12:44] [Render thread/INFO]: Renaming synthetic method lambda$onBeforeMessage$0(Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/aizistral/nochatreports/encryption/Encryptor;)V to md590d4e$lambda$onBeforeMessage$0$4 in nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
[07:12:44] [Render thread/WARN]: Discarding @Unique public method getAnimatedSkin in 3dskinlayers.mixins.json:DonorAbstractClientPlayerMixin from mod skinlayers because it already exists in net.minecraft.class_742
[07:12:45] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[07:12:45] [Render thread/INFO]: Mixing client.MixinYggdrasilUserApiService from nochatreports.mixins.json into com.mojang.authlib.yggdrasil.YggdrasilUserApiService
[07:12:47] [Render thread/INFO]: Setting user: Xunyu_awa
[07:12:47] [Render thread/INFO]: Mixing client.MixinToastComponent from nochatreports.mixins.json into net.minecraft.class_374
[07:12:47] [Render thread/INFO]: BetterPingDisplay mod loaded
[07:12:48] [Render thread/INFO]: Mixing server.MixinServerGamePacketListenerImpl from nochatreports.mixins.json into net.minecraft.class_3244
[07:12:48] [Render thread/WARN]: @Redirect conflict. Skipping carpet-extra.mixins.json:ServerPlayNetworkHandlerMixin from mod carpet-extra->@Redirect::carpetextra_removeHitPosCheck(Lnet/minecraft/class_243;Lnet/minecraft/class_243;)Lnet/minecraft/class_243; with priority 1000, already redirected by mixins.litematica.json:MixinServerPlayNetworkHandler from mod litematica->@Redirect::litematica_removeHitPosCheck(Lnet/minecraft/class_243;Lnet/minecraft/class_243;)Lnet/minecraft/class_243; with priority 1010
[07:12:48] [Render thread/WARN]: @Redirect conflict. Skipping mixins.tweakeroo.json:MixinServerPlayNetworkHandler from mod tweakeroo->@Redirect::tweakeroo_removeHitPosCheck(Lnet/minecraft/class_243;Lnet/minecraft/class_243;)Lnet/minecraft/class_243; with priority 1005, already redirected by mixins.litematica.json:MixinServerPlayNetworkHandler from mod litematica->@Redirect::litematica_removeHitPosCheck(Lnet/minecraft/class_243;Lnet/minecraft/class_243;)Lnet/minecraft/class_243; with priority 1010
[07:12:48] [EssentialClient Init Thread/ERROR]: Failed to fetch rule data
[07:12:48] [EssentialClient Init Thread/INFO]: Downloading deobfuscation mappings:  for the first launch
[07:12:49] [Render thread/INFO]: [MagicLib]: Mod initialized - Version: 0.6.200+a47eb26-beta
[07:12:49] [Render thread/INFO]: KONNICHIWA ZA WARUDO!
[07:12:49] [Render thread/INFO]: Default JVM text encoding is: GBK
[07:12:49] [Render thread/INFO]: Reading config file NoChatReports/NCR-Common.json...
[07:12:49] [Render thread/INFO]: Reading config file NoChatReports/NCR-Client.json...
[07:12:49] [Render thread/INFO]: Reading config file NoChatReports/NCR-ServerPreferences.json...
[07:12:49] [Render thread/INFO]: Reading config file NoChatReports/NCR-Encryption.json...
[07:12:49] [Render thread/INFO]: Writing config file NoChatReports/NCR-Common.json...
[07:12:49] [Render thread/INFO]: Writing config file NoChatReports/NCR-Client.json...
[07:12:49] [Render thread/INFO]: Writing config file NoChatReports/NCR-ServerPreferences.json...
[07:12:49] [Render thread/INFO]: Writing config file NoChatReports/NCR-Encryption.json...
[07:12:50] [EssentialClient Init Thread/ERROR]: Failed to downloads mappings!
java.io.FileNotFoundException: https://maven.fabricmc.net/net/fabricmc/yarn//yarn--v2.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at java.net.URL.openStream(URL.java:1161) ~[?:?]
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1068) ~[commons-io-2.11.0.jar:?]
	at me.senseiwells.essentialclient.utils.clientscript.MinecraftDeobfuscator.downloadAndCacheMappings(MinecraftDeobfuscator.java:104) ~[essential-client-1.19.3-1.3.2.jar:?]
	at me.senseiwells.essentialclient.utils.clientscript.MinecraftDeobfuscator.<clinit>(MinecraftDeobfuscator.java:59) ~[essential-client-1.19.3-1.3.2.jar:?]
	at me.senseiwells.essentialclient.EssentialClient.lambda$onInitialize$2(EssentialClient.java:67) ~[essential-client-1.19.3-1.3.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:12:51] [Render thread/INFO]: [WTHIT] Registering plugin waila:core at mcp.mobius.waila.plugin.core.WailaCore
[07:12:51] [Render thread/INFO]: [WTHIT] Registering plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[07:12:51] [Render thread/INFO]: [WTHIT] Using mcp.mobius.waila.plugin.core.pick.ObjectPicker as the object picker
[07:12:51] [Render thread/INFO]: [WTHIT] Plugin config reloaded
[07:12:51] [Render thread/INFO]: Mixing client.MixinClientPacketListener from nochatreports.mixins.json into net.minecraft.class_634
[07:12:51] [Render thread/WARN]: Found outdated translation keys in extension 'dev.dubhe.gugle.carpet.GcaExtension'!
These won't be supported in a later Carpet version!
Carpet will now try to map them to the correct keys in a best-effort basis
[07:12:51] [Render thread/WARN]: Found outdated translation keys in extension 'dev.dubhe.gugle.carpet.GcaExtension'!
These won't be supported in a later Carpet version!
Carpet will now try to map them to the correct keys in a best-effort basis
[07:12:51] [Render thread/INFO]: Carpet AMS Addition v1.3.5 载入成功
[07:12:51] [Render thread/INFO]: 开源链接：https://github.com/Minecraft-AMS/Carpet-AMS-Addition
[07:12:51] [Render thread/INFO]: BUG反馈：https://github.com/Minecraft-AMS/Carpet-AMS-Addition/issues
[07:12:51] [Render thread/WARN]: Found outdated translation keys in extension 'dev.dubhe.gugle.carpet.GcaExtension'!
These won't be supported in a later Carpet version!
Carpet will now try to map them to the correct keys in a best-effort basis
[07:12:51] [Render thread/WARN]: Found outdated translation keys in extension 'dev.dubhe.gugle.carpet.GcaExtension'!
These won't be supported in a later Carpet version!
Carpet will now try to map them to the correct keys in a best-effort basis
[07:12:52] [Render thread/WARN]: Found outdated translation keys in extension 'dev.dubhe.gugle.carpet.GcaExtension'!
These won't be supported in a later Carpet version!
Carpet will now try to map them to the correct keys in a best-effort basis
[07:12:52] [Render thread/INFO]: Ivan Carpet Addition 2.2.1 loaded
[07:12:52] [Render thread/INFO]: Thank you for using ICA!
[07:12:52] [Render thread/INFO]: ICA is open source, u can find it here: https://github.com/Ivan-1F/Ivan-Carpet-Addition
[07:12:52] [Render thread/INFO]: ICA is still in development, it may not work well
[07:12:52] [Render thread/INFO]: If u find any bug, please report them here: https://github.com/Ivan-1F/Ivan-Carpet-Addition/issues
[07:12:52] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[07:12:53] [Render thread/INFO]: [STDOUT]: Inventory HUD + has been initialized!
[07:12:55] [Render thread/INFO]: Client initialization...
[07:12:56] [Render thread/INFO]: [Tweak My Client for 1.19.3]: Mod initialized - Version: 3.4.303+867af56-beta (Public Beta)
[07:12:56] [Render thread/INFO]: Loading Xaero's Minimap - Stage 1/2
[07:12:59] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[07:12:59] [Render thread/INFO]: Loading Xaero's World Map - Stage 1/2

**Comment by Ivan-1F** [comment]
Duplicate with #15
